apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fibonacci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stamina11/fibonacci.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: fib
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
